title: 1xTP Portfolio
email: your-email@example.com
description: 1xTP cybersecurity portfolio.
baseurl: ""
url: "https://1xtp.github.io"
twitter_username: jekyllrb
github_username:  jekyll

plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-paginate-v2

future: false

collections:
  writeups:
    output: true
    permalink: /:collection/:path/

pagination:
  enabled: true
  collection: 'writeups'
  per_page: 5
  sort_field: 'date'
  sort_reverse: true
